module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'mecha-black': '#06090C',
        'mecha-gray': '#75787D',
        'mecha-mint': '#40BFAF',
        'mecha-dark': '#494C51',
        'mecha-light': '#B4B4BC',
        'mecha-brown': '#928072',
        'mecha-light-bg': '#F7F8FA',
        'mecha-light-text': '#23232a',
        'mecha-light-accent': '#40BFAF',
        'mecha-light-gray': '#B4B4BC',
        'mecha-light-brown': '#928072',
        'light-bg': '#F0DAD5',
        'light-fg': '#424658',
        'light-accent': '#C56B62',
        'light-card': '#D9A69F',
        'light-border': '#6C739C',
        'light-brown': '#DEA785',
        'light-shadow': '#BABBB155',
        'light-nav-active': '#C56B62',
        'light-nav-text': '#424658',
        'light-nav-inactive': '#6C739C',
        'light-chart-stroke': '#C56B62',
        'light-chart-fill': '#D9A69F',
        'dark-bg': '#000000',
        'dark-fg': '#DFDEDC',
        'dark-accent': '#00ACAC',
        'dark-card': '#6B7A8F',
        'dark-border': '#6B7A8F',
        'dark-brown': '#A6A7A2',
        'dark-shadow': '#000000AA',
        'dark-nav-active': '#00ACAC',
        'dark-nav-text': '#000000',
        'dark-nav-inactive': '#6B7A8F',
        'dark-chart-stroke': '#00ACAC',
        'dark-chart-fill': '#6B7A8F',
      },
    },
  },
  darkMode: 'class',
  plugins: [],
}; 